spring:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password: sa
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  profiles:
    active: ${active.profile:dev}
